#' Summary function for ctsemFit object
#'
#' Provides summary details for ctsemFit objects.
#' 
#' @param object ctsemFit object as generated by ctFit.
#' @param ... additional parameters to pass.
#' @return Summary of ctsemFit object
#' @method summary ctsemFit
#' @export
summary.ctsemFit<-function(object,...){

  outlist<-c()
#   asymptotes<-object$ctfitargs$asymptotes
  stationary<-object$ctfitargs$stationary
#   randomPredictors<-object$ctfitargs$randomPredictors
  out<-list()
  omxsummary<-getMethod("summary","MxModel")(object[[1]]) #get openmx summary
  
  n.latent<-object$ctmodelobj$n.latent
  n.TIpred<-object$ctmodelobj$n.TIpred
  n.TDpred<-object$ctmodelobj$n.TDpred
  n.manifest<-object$ctmodelobj$n.manifest
  
  latentNames<-object$ctmodelobj$latentNames
  manifestNames<-object$ctmodelobj$manifestNames
  
  

    
    
    DRIFT<-tryCatch({ object$mxobj$DRIFT$values}, error=function(e) e )
    tryCatch({  dimnames(DRIFT)<-list(latentNames,latentNames)}, error=function(e) e )
    outlist<-c(outlist,'DRIFT')
    
    discreteDRIFT<-tryCatch({ OpenMx::expm(DRIFT)}, error=function(e) e )
    tryCatch({  dimnames(discreteDRIFT)<-list(latentNames,latentNames)}, error=function(e) e )
    outlist<-c(outlist,'discreteDRIFT')
    
    outlist<-c(outlist,'discreteDRIFTstd')
    
    DRIFTHATCH<-tryCatch({ (DRIFT %x% diag(n.latent)) + (diag(n.latent) %x% DRIFT)}, error=function(e) e )
    
      MANIFESTVAR<-tryCatch({ object$mxobj$MANIFESTVAR$values}, error=function(e) e )
    tryCatch({  dimnames(MANIFESTVAR)<-list(manifestNames,manifestNames)}, error=function(e) e )
    outlist<-c(outlist,'MANIFESTVAR')
    
    CINT<-tryCatch({ object$mxobj$CINT$values}, error=function(e) e )
#     if(asymptotes==TRUE | stationary==TRUE) CINT <- tryCatch({ -DRIFT %*% CINT}, error=function(e) e )
    tryCatch({  rownames(CINT)<-latentNames}, error=function(e) e )
    outlist<-c(outlist,'CINT')
    
      discreteCINT<-tryCatch({ solve(DRIFT) %*%(discreteDRIFT - diag(n.latent)) %*% CINT}, error=function(e) e )
    tryCatch({  rownames(discreteCINT)<-latentNames}, error=function(e) e )
    outlist<-c(outlist,'discreteCINT')
    
  asymCINT<-tryCatch({ -solve(DRIFT) %*% CINT}, error=function(e) e )
    tryCatch({  rownames(asymCINT)<-latentNames}, error=function(e) e )
    outlist<-c(outlist,'asymCINT')
    
    

    
    DIFFUSION<-tryCatch({ object$mxobj$DIFFUSION$values}, error=function(e) e )
#     if(asymptotes==TRUE | stationary==TRUE) DIFFUSION <- tryCatch({ matrix(-DRIFTHATCH %*% rvectorize(DIFFUSION), nrow=n.latent, ncol=n.latent)}, error=function(e) e )
    tryCatch({  dimnames(DIFFUSION)<-list(latentNames,latentNames)}, error=function(e) e )
    outlist<-c(outlist,'DIFFUSION')
    
          discreteDIFFUSION<-tryCatch({ matrix(solve(DRIFTHATCH) %*% ((OpenMx::expm(DRIFTHATCH * 1)) - 
        (diag(n.latent) %x% diag(n.latent)) ) %*%rvectorize(DIFFUSION), nrow=n.latent) }, error=function(e) e )
    tryCatch({  dimnames(discreteDIFFUSION)<-list(latentNames,latentNames)}, error=function(e) e )
    outlist<-c(outlist,'discreteDIFFUSION')
    
            asymDIFFUSION<-tryCatch({ matrix(-solve(DRIFTHATCH) %*% cvectorize(DIFFUSION),nrow=n.latent)}, error=function(e) e )
    tryCatch({  dimnames(asymDIFFUSION)<-list(latentNames,latentNames)}, error=function(e) e )
    outlist<-c(outlist,'asymDIFFUSION')
    
            asymDIFFUSIONdiag<-tryCatch({ diag(diag(asymDIFFUSION),n.latent)}, error=function(e) e )
            asymDIFFUSIONstd<-tryCatch({ suppressWarnings(solve(sqrt(asymDIFFUSIONdiag)) %*% asymDIFFUSION %*% solve(sqrt(asymDIFFUSIONdiag)))}, error=function(e) e )
    tryCatch({  dimnames(asymDIFFUSIONstd)<-list(latentNames,latentNames)}, error=function(e) e )
    outlist<-c(outlist,'asymDIFFUSIONstd')
    
   #std dev of affecting latent divided by std dev of affected latent
            standardiser<-tryCatch({ suppressWarnings(rep(sqrt(diag(asymDIFFUSION)),each=n.latent) / rep(diag(sqrt(asymDIFFUSION)),times=n.latent))}, error=function(e) e )
            discreteDRIFTstd<-tryCatch({ discreteDRIFT * standardiser    }, error=function(e) e )
    tryCatch({  dimnames(discreteDRIFTstd)<-list(latentNames,latentNames)}, error=function(e) e )
    #added to outlist above
    
            asymTOTALVAR<-tryCatch({ asymDIFFUSION }, error=function(e) e )#set totalvar to t0withinvar to begin
    tryCatch({  dimnames(asymTOTALVAR)<-list(latentNames,latentNames)}, error=function(e) e )
    outlist<-c(outlist,'asymTOTALVAR')
    
    
            asymTOTALVARdiag<-tryCatch({ diag(diag(asymTOTALVAR),n.latent)}, error=function(e) e )
            asymTOTALVARstd<-tryCatch({ suppressWarnings(solve(sqrt(asymTOTALVARdiag)) %*% asymTOTALVAR %*% solve(sqrt(asymTOTALVARdiag)))}, error=function(e) e )
    tryCatch({  dimnames(asymTOTALVARstd)<-list(latentNames,latentNames)}, error=function(e) e )
    outlist<-c(outlist,'asymTOTALVARstd')
    
    
    if('T0VAR' %in% stationary){ #then include base T0 matrices
      T0VAR<-tryCatch({ object$mxobj$T0VAR$values}, error=function(e) e )
      tryCatch({  dimnames(T0VAR)<-list(latentNames,latentNames)}, error=function(e) e )
      outlist<-c(outlist,'T0VAR')
      
      T0TOTALVAR<-tryCatch({ T0VAR }, error=function(e) e )#set t0totalvar to t0withinvar to begin
      tryCatch({  dimnames(T0TOTALVAR)<-list(latentNames,latentNames)}, error=function(e) e )
      outlist<-c(outlist,'T0TOTALVAR')
      
      T0VARdiag<-tryCatch({ diag(diag(T0VAR),n.latent)}, error=function(e) e )
      T0VARstd<-tryCatch({ suppressWarnings(solve(sqrt(T0VARdiag)) %*% T0VAR %*% solve(sqrt(T0VARdiag)))}, error=function(e) e )
      tryCatch({  dimnames(T0VARstd)<-list(latentNames,latentNames)}, error=function(e) e )
      outlist<-c(outlist,'T0VARstd')
      
    } # end T0VAR matrices
      
  if('T0MEANS' %in% stationary){ #then include base T0 matrices
      T0MEANS<-tryCatch({ object$mxobj$T0MEANS$values}, error=function(e) e )
      tryCatch({  rownames(T0MEANS)<-latentNames}, error=function(e) e )
      outlist<-c(outlist,'T0MEANS')
}
    
    
    #trait matrices
    if(any(object$ctmodelobj$TRAITVAR != 0)) {
      
      TRAITVAR<-tryCatch({ object$mxobj$TRAITVAR$values}, error=function(e) e )
      tryCatch({  dimnames(TRAITVAR)<-list(latentNames,latentNames)}, error=function(e) e )
      outlist<-c(outlist,'TRAITVAR')
      
      discreteTRAITVAR<-tryCatch({ solve(DRIFT) %*% (OpenMx::expm(DRIFT * 1)) - solve(DRIFT)}, error=function(e) e )
      tryCatch({  dimnames(discreteTRAITVAR)<-list(latentNames,latentNames)}, error=function(e) e )
      outlist<-c(outlist,'discreteTRAITVAR')
      
        asymTRAITVAR<-tryCatch({ solve(DRIFT) %*% TRAITVAR %*% t(solve(DRIFT))}, error=function(e) e )
      tryCatch({  dimnames(asymTRAITVAR)<-list(latentNames,latentNames)}, error=function(e) e )
      outlist<-c(outlist,'asymTRAITVAR')
      
          asymTRAITVARdiag<-tryCatch({ diag(diag(asymTRAITVAR),n.latent)}, error=function(e) e )
          asymTRAITVARstd<-tryCatch({ suppressWarnings(solve(sqrt(asymTRAITVARdiag)) %*% asymTRAITVAR %*% solve(sqrt(asymTRAITVARdiag)))}, error=function(e) e )
      tryCatch({  dimnames(asymTRAITVARstd)<-list(latentNames,latentNames)}, error=function(e) e )
      outlist<-c(outlist,'asymTRAITVARstd')
      
          asymTOTALVAR<-tryCatch({ asymDIFFUSION + asymTRAITVAR}, error=function(e) e )
      tryCatch({  dimnames(asymTOTALVAR)<-list(latentNames,latentNames)}, error=function(e) e )
      
          asymTOTALVARdiag<-tryCatch({ diag(diag(asymTOTALVAR),n.latent)}, error=function(e) e )
          asymTOTALVARstd<-tryCatch({ suppressWarnings(solve(sqrt(asymTOTALVARdiag)) %*% asymTOTALVAR %*% solve(sqrt(asymTOTALVARdiag)))}, error=function(e) e )
      tryCatch({  dimnames(asymTOTALVARstd)<-list(latentNames,latentNames)}, error=function(e) e )

      if('T0TRAITEFFECT' %in% stationary) { #then include T0 trait matrices
        
         T0TRAITEFFECT<-tryCatch({ object$mxobj$T0TRAITEFFECT$values}, error=function(e) e )
        tryCatch({  dimnames(T0TRAITEFFECT)<-list(latentNames,latentNames)}, error=function(e) e )
        outlist<-c(outlist,'T0TRAITEFFECT')
        
         T0TRAITVAR<-tryCatch({ T0TRAITEFFECT %*% TRAITVAR %*% t(T0TRAITEFFECT) }, error=function(e) e )#is this valid?
        tryCatch({  dimnames(T0TRAITVAR)<-list(latentNames,latentNames)}, error=function(e) e )
        outlist<-c(outlist,'T0TRAITVAR')
        
        
         T0TRAITVARdiag<-tryCatch({ suppressWarnings(sqrt(diag(diag(T0TRAITVAR),n.latent)))}, error=function(e) e )
         T0TRAITVARstd<-tryCatch({ solve(T0TRAITVARdiag) %*% T0TRAITVAR %*% solve(T0TRAITVARdiag)}, error=function(e) e )
        tryCatch({  dimnames(T0TRAITVARstd)<-list(latentNames,latentNames)}, error=function(e) e )
        outlist<-c(outlist,'T0TRAITVARstd')
        
         T0TOTALVAR<-tryCatch({ T0TRAITVAR+T0VAR}, error=function(e) e )
        tryCatch({  dimnames(T0TOTALVAR)<-list(latentNames,latentNames)}, error=function(e) e )
        
         T0TOTALVARdiag<-tryCatch({ diag(diag(T0TOTALVAR),n.latent)}, error=function(e) e )
         T0TOTALVARstd<-tryCatch({ suppressWarnings(solve(sqrt(T0TOTALVARdiag)) %*% T0TOTALVAR %*% solve(sqrt(T0TOTALVARdiag)))}, error=function(e) e )
        tryCatch({  dimnames(T0TOTALVARstd)<-list(latentNames,latentNames)}, error=function(e) e )
        
      } #end T0 trait matrices
    }#end trait matrices
    
    
    
    
    #TIpred matrices
    if(n.TIpred > 0) {
      TIpredNames<-object$ctmodelobj$TIpredNames      
#        if(asymptotes==FALSE) TIPREDEFFECT<-tryCatch({object$mxobj$TIPREDEFFECT$values}, error=function(e) e )
#       if(asymptotes==TRUE) 
        TIPREDEFFECT<-tryCatch({-DRIFT %*% object$mxobj$TIPREDEFFECT$values}, error=function(e) e )
      tryCatch({  dimnames(TIPREDEFFECT)<-list(latentNames,TIpredNames)}, error=function(e) e )
      outlist<-c(outlist,'TIPREDEFFECT')
        
#       if (randomPredictors==TRUE) TIPREDVAR<-tryCatch({object$mxobj$S$values[TIpredNames,TIpredNames] }, error=function(e) e )
#       if(randomPredictors==FALSE) 
        TIPREDVAR<-tryCatch({var(object$datawide[,TIpredNames]) }, error=function(e) e )
      outlist<-c(outlist,'TIPREDVAR')
      
      
       TIPREDVARdiag<-tryCatch({diag(diag(TIPREDVAR),n.TIpred)}, error=function(e) e )
      TIPREDVARstd<-tryCatch({suppressWarnings(solve(sqrt(TIPREDVARdiag)) %*% TIPREDVAR %*% solve(sqrt(TIPREDVARdiag)))}, error=function(e) e )
      tryCatch({  dimnames(TIPREDVARstd)<-list(TIpredNames,TIpredNames)}, error=function(e) e )
      outlist<-c(outlist,'TIPREDVARstd')
      
       discreteTIPREDEFFECT<-tryCatch({solve(DRIFT) %*%(discreteDRIFT - diag(n.latent)) %*% TIPREDEFFECT }, error=function(e) e )#disrete from continuous
      tryCatch({  dimnames(discreteTIPREDEFFECT)<-list(latentNames,TIpredNames) }, error=function(e) e )
      outlist<-c(outlist,'discreteTIPREDEFFECT')
      
        asymTIPREDEFFECT<-tryCatch({solve(diag(n.latent)-discreteDRIFT)  %*%  (discreteTIPREDEFFECT)}, error=function(e) e )
          tryCatch({  dimnames(asymTIPREDEFFECT)<-list(latentNames,TIpredNames)}, error=function(e) e )
      outlist<-c(outlist,'asymTIPREDEFFECT')
    
      #sqrt of affecting latent variance divided by sqrt of affected
           standardiser<-tryCatch({suppressWarnings(rep(sqrt(diag(TIPREDVAR)),each=n.latent) / rep(diag(sqrt(asymDIFFUSION)),times=n.TIpred))}, error=function(e) e )
          asymTIPREDEFFECTstd<-tryCatch({asymTIPREDEFFECT * standardiser}, error=function(e) e )
            tryCatch({  dimnames(asymTIPREDEFFECTstd)<-list(latentNames,TIpredNames)}, error=function(e) e )
      outlist<-c(outlist,'asymTIPREDEFFECTstd')
      
           addedTIPREDVAR <-tryCatch({asymTIPREDEFFECT %*% TIPREDVAR %*% t(asymTIPREDEFFECT) }, error=function(e) e )#valid?
            tryCatch({  dimnames(addedTIPREDVAR)<-list(latentNames,latentNames)}, error=function(e) e )
      outlist<-c(outlist,'addedTIPREDVAR')
      
             addedTIPREDVARdiag<-tryCatch({diag(diag(addedTIPREDVAR),n.latent)}, error=function(e) e )
      addedTIPREDVARstd<-tryCatch({suppressWarnings(solve(sqrt(addedTIPREDVARdiag)) %*% addedTIPREDVAR %*% solve(sqrt(addedTIPREDVARdiag)))}, error=function(e) e )
            tryCatch({  dimnames(addedTIPREDVARstd)<-list(latentNames,latentNames)}, error=function(e) e )
      outlist<-c(outlist,'addedTIPREDVARstd')
      
           asymTOTALVAR<-tryCatch({asymTOTALVAR + addedTIPREDVAR}, error=function(e) e )
            tryCatch({  dimnames(asymTOTALVAR)<-list(latentNames,latentNames)}, error=function(e) e )
      
              asymTOTALVARdiag<-tryCatch({diag(diag(asymTOTALVAR),n.latent)}, error=function(e) e )
            asymTOTALVARstd<-tryCatch({suppressWarnings(solve(sqrt(asymTOTALVARdiag)) %*% asymTOTALVAR %*% solve(sqrt(asymTOTALVARdiag)))}, error=function(e) e )
              tryCatch({  dimnames(asymTOTALVARstd)<-list(latentNames,latentNames)}, error=function(e) e )
      
    if('TOTIPRED' %in% stationary) { #include TIPRED T0 matrices
      T0TIPREDEFFECT<-tryCatch({object$mxobj$T0TIPREDEFFECT$values}, error=function(e) e )
      tryCatch({  dimnames(T0TIPREDEFFECT)<-list(latentNames,TIpredNames)}, error=function(e) e )
      outlist<-c(outlist,'T0TIPREDEFFECT')
      
      #sqrt of affecting latent variance divided by sqrt of affected
      standardiser<-tryCatch({suppressWarnings(rep(sqrt(diag(TIPREDVAR)),each=n.latent) / rep(diag(sqrt(T0VAR)),times=n.TIpred))}, error=function(e) e )
      T0TIPREDEFFECTstd<-tryCatch({T0TIPREDEFFECT * standardiser}, error=function(e) e )
      tryCatch({  dimnames(T0TIPREDEFFECTstd)<-list(latentNames,TIpredNames)}, error=function(e) e )
      outlist<-c(outlist,'T0TIPREDEFFECTstd')
      
     
      addedT0TIPREDVAR<-tryCatch({T0TIPREDEFFECT %*% TIPREDVAR %*% t(T0TIPREDEFFECT)}, error=function(e) e )#is this valid?
      tryCatch({  dimnames(addedT0TIPREDVAR)<-list(latentNames,latentNames)}, error=function(e) e )
      outlist<-c(outlist,'addedT0TIPREDVAR')
      
      T0TOTALVAR<-tryCatch({addedT0TIPREDVAR+T0TOTALVAR }, error=function(e) e )#update totalvar
      tryCatch({  dimnames(T0TOTALVAR)<-list(latentNames,latentNames)}, error=function(e) e )
      
      T0TOTALVARdiag<-tryCatch({diag(diag(T0TOTALVAR),n.latent)}, error=function(e) e )
      T0TOTALVARstd<-tryCatch({suppressWarnings(solve(sqrt(T0TOTALVARdiag)) %*% T0TOTALVAR %*% solve(sqrt(T0TOTALVARdiag)))}, error=function(e) e )
      tryCatch({  dimnames(T0TOTALVARstd)<-list(latentNames,latentNames)}, error=function(e) e )

    } #end T0 TIPRED matrices
    
    } # end TIPRED matrices
    
    
    
    if(n.TDpred > 0) {
      
      TDpredtype<-object$ctfitargs$TDpredtype
      
      TDpredNames<-object$ctmodelobj$TDpredNames      
      
      TDPREDEFFECT<-tryCatch({object$mxobj$TDPREDEFFECT$values}, error=function(e) e )
      tryCatch({  dimnames(TDPREDEFFECT)<-list(latentNames,TDpredNames)}, error=function(e) e )
      outlist<-c(outlist,'TDPREDEFFECT')
      

      if(TDpredtype=='level') discreteTDPREDEFFECT<- solve(DRIFT) %*% (OpenMx::expm(DRIFT) - diag(n.latent)) %*% TDPREDEFFECT
      if(TDpredtype=='impulse') discreteTDPREDEFFECT<- OpenMx::expm(DRIFT) %*% TDPREDEFFECT
      tryCatch({  dimnames(discreteTDPREDEFFECT)<-list(latentNames,TDpredNames)}, error=function(e) e )
      outlist<-c(outlist,'discreteTDPREDEFFECT')
      
#       if(stablemodel==TRUE){
      if(TDpredtype=='level') asymTDPREDEFFECT<- -solve(DRIFT) %*% TDPREDEFFECT
      if(TDpredtype=='impulse') asymTDPREDEFFECT<- matrix(0,nrow=n.latent,ncol=n.TDpred)
      tryCatch({  dimnames(asymTDPREDEFFECT)<-list(latentNames,TDpredNames)}, error=function(e) e )
      outlist<-c(outlist,'asymTDPREDEFFECT')
#       }
      
#       if (randomPredictors==TRUE) 
        TDPREDVAR<-tryCatch({object$mxobj$TDPREDVAR$values }, error=function(e) e )
      tryCatch({  dimnames(TDPREDVAR)<-list(TDpredNames,TDpredNames)}, error=function(e) e )
      outlist<-c(outlist,'TDPREDVAR')
#       if(randomPredictors==FALSE) TDPREDVAR<-tryCatch({var(object$datawide[,paste0(TDpredNames,'_T',0:(Tpoints-1))]) }, error=function(e) e )
      
      #std dev of affecting latent divided by std dev of affected latent - how to do this for td predictors, both types?
#       standardiser<-tryCatch({ 1 / rep(diag(sqrt(asymDIFFUSION)),times=n.latent)}, error=function(e) e )
#       TDPREDEFFECTstd<-tryCatch({ TDPREDEFFECT * standardiser    }, error=function(e) e )
#       tryCatch({  dimnames(TDPREDEFFECTstd)<-list(latentNames,TDpredNames)}, error=function(e) e )
#       outlist<-c(outlist,'TDPREDEFFECTstd')
      
      TDPREDVARdiag<-tryCatch({diag(diag(TDPREDVAR))}, error=function(e) e )
      TDPREDVARstd<-tryCatch({suppressWarnings(solve(sqrt(TDPREDVARdiag)) %*% TDPREDVAR %*% solve(sqrt(TDPREDVARdiag)))}, error=function(e) e )
      tryCatch({  dimnames(TDPREDVARstd)<-list(TDpredNames,TDpredNames)}, error=function(e) e )
      outlist<-c(outlist,'TDPREDVARstd')
      
    } # end TIpred section
   
    ctsummary<-mget(outlist) 
  #end summary from continuous params
  
  ##Openmx params
browser()
  omxsummary<-c(omxsummary['modelName'],omxsummary['wallTime'],omxsummary['mxVersion'],omxsummary['timestamp'],
    omxsummary['parameters'], omxsummary['estimatedParameters'], omxsummary['CI'],
    omxsummary['AIC.Mx'],omxsummary['BIC.Mx'],omxsummary['observedStatistics'],
    omxsummary['npsolMessage'],
    omxsummary['degreesOfFreedom'],omxsummary['Minus2LogLikelihood'] )
  
  output<-ctsummary
  output$omxsummary<-omxsummary
  
  return(output)
}
